<?php

  function dna_helix_menu(){
    $items['dna_helix'] = array(
      'title' => 'Let\'s Play Polymerase!',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('dna_helix_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    $items['dna_results'] = array(
      'title' => 'The results are in...',
      'page callback' => 'results',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }

  function dna_helix_form(){
    $form['user_strand'] = array(
      '#title' => 'strand',
      '#type' => 'textfield',
      '#description' => t('Enter a strand of DNA and we\'ll give you a corisponding strand'),
      '#element_validate' => array('element_validate_accepted_chars'),
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('submit'),
    );
    return $form;
  }
  function element_validate_accepted_chars($element){
    $accepted_chars = ["A", "T", "C", "G"];
    $strand_array = str_split(strtoupper($element['#value']));
    foreach($strand_array as $letter){
      if(!in_array($letter, $accepted_chars)){
        form_error($element, t('Human DNA is only made up of four nucleotides, represented by the letters A, T, C, and G. Please enter a string only containing these letters.'));
        break;
      }
    }
  }

  function dna_helix_form_submit($form, &$form_state){
    $strand = $form_state['values']['user_strand'];
    $_SESSION['results'] = transform_strand($strand);
    $form_state['redirect'] = 'dna_results';
  }

  function transform_strand($strand){
    $output = "";
    $strand = str_split(strtoupper($strand));
    foreach ($strand as $key => $value) {
      if($value == "A"){
        $output .= "T";
      }
      elseif($value == "T"){
        $output .= "A";
      }
      elseif($value == "G"){
        $output .= "C";
      }
      elseif ($value =="C") {
        $output .= "G";
      }
    }
    return $output;
  }

  function results(){
      return $_SESSION['results'];
  }
